version: "3.8"

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hyuki

  redis:
    image: redis:6.2.3
    ports:
      - "6370:6379"
    command: redis-server /etc/redis.conf
    volumes:
      - ./local-redis.conf:/etc/redis.conf
    restart: always
