server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: hyuki-app
#
#  profiles:
#    group:
#      test: logger
#      local: logger, data
#      dev: logger, data
#      prod: logger, data
#    active: local
#
#  redis:
#    host: localhost
#    port: 6370
#
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        logger-level: full
#
#  circuitbreaker:
#    enabled: true
#
